'''THIS IS THE CODE FOR ECAT TEST. It includes following features:
1.This single code can take three type of tests (Pre-Engineering, Pre-Medical and ICS).
2.There are total 10 questions in each test (English = 1, Chemistry/Computer = 3, Physics = 3, Mathematics/Biology = 3).
3.By using UDF (result_calculator) displays compelete Result (obtained marks, Percentage, skipped questions, correct answers, wrong answers) and also tells admission eligibility
4.It also tells the user which portion of questions he/she is attempting
5.User can answer skipped questions later (have made UDF for it "answer_to_skip")
6.When skipped questions will be zero and user had attempted all the questions test will be automatically submitted and result will be diaplayed. Moreover user can submit the test anytime at any question'''

import random
def result_calculator(a, b, c, d):
    '''a = skipped questions, b = total marks, c = correct answers, d = wrong answers'''
    print("Submitted")
    print(f"Your skipped questions are: {a}")
    print(f"Your marks are: {b}")
    print(f"your correctly answered questions are: {c}")
    print(f"your wrong answers are: {d}")
    percentage = (score / 40) * 100
    print(f"your percentage is: {percentage:.2f}")
    if percentage >= 40:
        print("You are eligible for Admission", "\U0001F389")
    else:
        print("Sorry!,You are not eligible for Admission", "\n", "Try next time", "\U0001F917")



def answer_to_skip():
    global skipped, skip, answer, score, correct_answers, wrong_answers
    for k in skip:
        print(Q[k][0])
        for j in range(1, 7):
            print(Q[k][j], "\n", end="")
        print("")
        answer = input("enter your answer as a,b,c,d,e,f:")
        skipped -= 1
        if answer == "e":
            skip.append(k)
            skipped += 1
            print(f"You have skipped {skipped} questions")
            p = input("Do you want to answer them? yes/no:")
            if p == "yes":
                answer_to_skip()
            else:
                result_calculator(skipped, score, correct_answers, wrong_answers)
                break
        if skipped == 0:
            result_calculator(skipped, score, correct_answers, wrong_answers)
            quit()
def ecat():
    global test, skipped, score, attempts, correct_answers, wrong_answers, skip, inter, questions_ics, questions_M, questions_E, Q, answer
    print("ECAT TEST 2023")
    print(
        '◈Each correct option has 4 Marks.\n◈Each wrong option has negative 1 mark.\n◈Read all Questions and Options Care'
        'fully\n◈If there is problem with questions please inform the instructor.\n◈To start test please enter "start"\n')
    print("Best of luck")
    test = input("Select the category\n  1)pre-engineering\n 2)ics\n 3)pre-medical\n ")
    skipped = 0
    score = 0
    attempts = 10
    correct_answers = 0
    wrong_answers = 0
    skip = []
    inter = 0
    questions_ics = (("Select the correct spellings", "a. essecne", "b. essence", "c. ecense",
                      "d. exence", "e. skip", "f. submit", "b. essence"), (
                         "The term ‘Computer’ is derived from__________?", "a. Latin", "b. German",
                         "c. Arabic", "d. French", "e. skip", "f. submit", "a. Latin"), (
                         "Who is the father of Internet ?", "a. Charles Babbage", "b. carry minoty",
                         "c. Denis Riche", "d. Martin Cooper", "e. skip", "f. submit",
                         "d. Martin Cooper"), (
                         "What type of operating system MS-DOS is?", "a. Command Line Interface",
                         "b. Graphical User Interface", "c. Multitasking", "d. Menu Driven Interface",
                         "e. skip", "f. submit", "a. Command Line Interface"), (
                         "Current produced by moving the loop of wire across a magnetic field is called",
                         "a. A.C current", "b. D.C current", "c. conductance", "d. Mean square current",
                         "e. skip", "f. submit", "d. Mean square current"), (
                         "A wire of uniform area of cross-section A length L and resistance R is cut into two parts. The resistivity of each part",
                         "a. Remains the same", "b. Is doubled", "c. Is halved", "d. Becomes zero",
                         "e. skip", "f. submit", "a. Remains the same"), (
                         "Emf generated by A.C dynamo depends upon", "a. Number of turns in the coil",
                         "b. Magnetic field strength", "c. Frequency of rotation", "d. All of above",
                         "e. skip", "f. submit", "d. all of above"), (
                         "(Z, .) is not a group because", "a. ‘.’ is not commutative",
                         "b. ‘.’ is not associative", "c. ‘.’ is not associative",
                         "d.  It has not inverse w.r.t. ‘.’", "e. skip", "f. submit",
                         "d.  It has not inverse w.r.t. ‘.’"), (
                         "Tick the false statement", "a. ‘÷’ is not a binary operation on N",
                         "b.  ‘+’ is a binary operation on N", "c. ‘–’ is a binary operation on N",
                         "d.  ‘×’ is a binary operation on N", "e. skip", "f. submit",
                         "c. ‘–’ is a binary operation on N"), (
                         " Degree of x4 + 2x – 1 is", "a.  0", "b. 1", "c. -2", "d. 4", "e. skip",
                         "f. submit", "d. 4"))
    questions_E = (("Select the correct spellings", "a. essecne", "b. essence", "c. ecense",
                    "d. exence", "e. skip", "f. submit", "b. essence"), (
                       "Pentane and 2-methyl butane have the same", "a. Boiling point",
                       "b. Melting point", "c. Percentage composition", "d. Structural formula",
                       "e. skip", "f. submit", "c. Percentage composition"), (
                       " Geometric isomerism is usually found in", "a. Alkanes", "b. Alkenes",
                       "c. Alkynes", "d. Esters", "e. skip", "f. submit", "b. Alkenes"), (
                       "Octane number 2 2 4-trimethyl pentane is", "a. 100", "b. 90", "c. 80", "d. 70",
                       "e. skip", "f. submit", "a. 100"), (
                       "Current produced by moving the loop of wire across a magnetic field is called",
                       "a. A.C current", "b. D.C current", "c. conductance", "d. Mean square current",
                       "e. skip", "f. submit", "d. Mean square current"), (
                       "A wire of uniform area of cross-section A length L and resistance R is cut into two parts. The resistivity of each part",
                       "a. Remains the same", "b. Is doubled", "c. Is halved", "d. Becomes zero",
                       "e. skip", "f. submit", "a. Remains the same"), (
                       "Emf generated by A.C dynamo depends upon", "a. Number of turns in the coil",
                       "b. Magnetic field strength", "c. Frequency of rotation", "d. All of above",
                       "e. skip", "f. submit", "d. all of above"), (
                       "(Z, .) is not a group because", "a. ‘.’ is not commutative",
                       "b. ‘.’ is not associative", "c. ‘.’ is not associative",
                       "d.  It has not inverse w.r.t. ‘.’", "e. skip", "f. submit",
                       "d.  It has not inverse w.r.t. ‘.’"), (
                       "Tick the false statement", "a. ‘÷’ is not a binary operation on N",
                       "b.  ‘+’ is a binary operation on N", "c. ‘–’ is a binary operation on N",
                       "d.  ‘×’ is a binary operation on N", "e. skip", "f. submit",
                       "c. ‘–’ is a binary operation on N"), (
                       " Degree of x4 + 2x – 1 is", "a.  0", "b. 1", "c. -2", "d. 4", "e. skip",
                       "f. submit", "d. 4"))
    questions_M = (("Select the correct spellings", "a. essecne", "b. essence", "c. ecense",
                    "d. exence", "e. skip", "f. submit", "b. essence"), (
                       "Pentane and 2-methyl butane have the same", "a. Boiling point",
                       "b. Melting point", "c. Percentage composition", "d. Structural formula",
                       "e. skip", "f. submit", "c. Percentage composition"), (
                       " Geometric isomerism is usually found in", "a. Alkanes", "b. Alkenes",
                       "c. Alkynes", "d. Esters", "e. skip", "f. submit", "b. Alkenes"), (
                       "Octane number 2 2 4-trimethyl pentane is", "a. 100", "b. 90", "c. 80", "d. 70",
                       "e. skip", "f. submit", "a. 100"), (
                       "Current produced by moving the loop of wire across a magnetic field is called",
                       "a. A.C current", "b. D.C current", "c. conductance", "d. Mean square current",
                       "e. skip", "f. submit", "d. Mean square current"), (
                       "A wire of uniform area of cross-section A length L and resistance R is cut into two parts. The resistivity of each part",
                       "a. Remains the same", "b. Is doubled", "c. Is halved", "d. Becomes zero",
                       "e. skip", "f. submit", "a. Remains the same"), (
                       "Emf generated by A.C dynamo depends upon", "a. Number of turns in the coil",
                       "b. Magnetic field strength", "c. Frequency of rotation", "d. All of above",
                       "e. skip", "f. submit", "d. all of above"), (
                       " The mechanism of regulation, generally between organism and its environment, of solutes and the gain and the loss of water is called",
                       "a. Homeostasis", "b. Homeostasis", "c. Osmoregulation", "d. Thermoregulation",
                       "e. skip", "f. submit", "c. Osmoregulation"), (
                       "Fungi which get their food directly from dead organic matter are called?",
                       "a. Parasitic fungi", "b. Predators", "c. Mutualists", "d. Decomposers",
                       "e. skip", "f. submit", "d. Decomposers"), (
                       "Seeds are dormant in conditions of", "a. Water scarcity", "b. Low temperature",
                       "c. Harsh Winters", "d. All of these", "e. skip", "f. submit",
                       "d. All of these"))
    for i in range(attempts):
        if test == "1" or inter == "1":
            Q = questions_ics
        if test == "2" or inter == "2":
            Q = questions_E
        if test == "3" or inter == "3":
            Q = questions_M
        if i == 0:
            print("ENGLISH PORTION:")
        if i == 1:
            if test == "ics":
                print("COMPUTER PORTION:")
            else:
                print("CHEMISTRY PORTION:")
        if i == 4:
            print("PHYSICS PORTION:")
        if i == 7:
            if test == "pre-medical":
                print("BIOLOGY PORTION:")
            else:
                print("MATHEMATICS PORTION:")
        print(Q[i][0])
        for h in range(1, 7):
            print(Q[i][h], "\n", end="")
        print("")
        answer = input("enter your answer as a,b,c,d,e,f:")
        attempts -= 1
        if answer == "e":
            skipped += 1
            skip.append(i)
            continue
        if answer == "f":
            print(f"You have skipped {skipped} questions")
            if skipped != 0:
                p = input("Do you want to answer them? yes/no:")
                if p == "yes":
                    answer_to_skip()
                    break
                else:
                    result_calculator(skipped, score, correct_answers, wrong_answers)
                    break
        if answer == Q[i][7][0]:
            score += 4
            correct_answers += 1
        else:
            score += -1
            wrong_answers += 1
        if attempts == 0 and skipped == 0:
            result_calculator(skipped, score, correct_answers, wrong_answers)
        if skipped != 0 and attempts == 0:
            print(f"You have skipped {skipped} questions")
            if skipped != 0:
                p = input("Do you want to answer them? yes/no:")
                if p == "yes":
                    answer_to_skip()
                else:
                    result_calculator(skipped, score, correct_answers, wrong_answers)
                    break

r = 0
while r < 1:
    name_list = ["Afeef Obaid", "Areesha Fatima","Bahauddin Hassan"]
    roll_list = ["ecatafob26", "ecatarfa17", "ecatbaha19"]
    ask = input("Enter your name please:")
    if ask in name_list:
        password = input("Enter your password please:")
        if password in roll_list:
            r += 1
            start = input("Enter START\n")
            if start == START:
                ecat()
    if ask not in name_list:
        ask_ = input("You haven't applied for test. do you want to take it(y/n): ")
        if ask_ == "y" or ask_ == "Y":
            password = ''
            subjects = ['']
            paid_chalan = {}
            chalan_list = {'': ''}
            temp_roll = ''
            temp_chalan = ''
            flag = 0
            confirm_s = '0'
            confirm = 'n'
            cnic = input('Enter your CNIC:')
            name = input('Enter Name you want to register:')
            length = 8
            digit = '1234567890'
            if cnic not in chalan_list:
                while temp_chalan in chalan_list:
                    for i in range(length):
                        a = random.choice(digit)
                        temp_chalan += str(a)
                temp_chalan = temp_chalan + cnic[-1:-7:-1]
                chalan_list[cnic] = temp_chalan
                paid_chalan[temp_chalan + 't'] = name
                print()
                print('Your chalan number is', temp_chalan)
            temp_chalan = input('Enter paid chalan number ends with t:')
            if temp_chalan in paid_chalan:
                for i in range(6):
                    a = random.choice(digit)
                    temp_roll += str(a)
            roll_list.append(temp_roll)
            name_list.append(name)
            print()
            print('Your roll number is', temp_roll)
            roll = input('Please Enter Your Roll Number:')
            if name in name_list:
                if roll in roll_list:
                    start = input("Enter START\n")
                    if start == "START":
                        ecat()
                        r+=1;
            else:
                print('something went wrong')
